storage: ./storage
plugins: ./plugins
middlewares:
  audit:
    enabled: true
web:
  title: shlifedev's packages
  
# https://verdaccio.org/docs/configuration#authentication
max_body_size: 100mb  
auth:
  htpasswd:
    file: ./htpasswd
    # 설정시 회원가입 가능, 현재는 어드민이 있으므로 비활성화
    max_users: -1
# https://verdaccio.org/docs/configuration#uplinks
# 내 서버에 파일이 없는경우 여기에서 다운로드
uplinks:
  openupm:
    url: https://package.openupm.com
    cache : false
  unity:
    url: https://packages.unity.com
    cache : false
    
packages: 
  '**': 
    access: shlifedev
    publish: shlifedev
    unpublish: shlifedev  
 
  '@shlifedev/*':
    access: shlifedev
    publish: shlifedev
    unpublish: shlifedev 
   
   
server:
  keepAliveTimeout: 60
  # Allow `req.ip` to resolve properly when Verdaccio is behind a proxy or load-balancer
  # See: https://expressjs.com/en/guide/behind-proxies.html
  # trustProxy: '127.0.0.1'
  

# https://verdaccio.org/docs/configuration#listen-port
listen:  
  - 0.0.0.0:4873    
            #https:
            #key: /home/shlifedev/.config/verdaccio/verdaccio-key.pem
            #cert: /home/shlifedev/.config/verdaccio/verdaccio-cert.pem     
            
            
# https:
#   key: ./path/verdaccio-key.pem
#   cert: ./path/verdaccio-cert.pem
#   ca: ./path/verdaccio-csr.pem
